# Generated by Django 4.0.3 on 2022-03-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newupdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('update_img', models.ImageField(upload_to='pics')),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
